import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";
import Picture from "./components/picture";

export default function Home() {
  const pictures = api.picture.getAll.useQuery().data;
  console.log(`pictures: ${pictures?.join(", ")}`);
  const productions = api.production.getAll.useQuery().data;
  console.log(productions?.join(", "));
  const replace = {
    width: 300,
    height: 400,
  };
  // sizes 200, 300, 400, 500, 600, 700, 800, 900, 1000
  return (
    <>
      <Head>
        <title>Leah Brown's Portfolio</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#bdc9ee] to-[#7c7d91]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-slate-50 sm:text-[5rem] ">
            Leah <span className="text-[hsl(234,42%,52%)]">R. </span> Brown
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            {pictures?.map((picture) => (
              <Picture
                key={picture.id}
                url={`https://picsum.photos/${picture.width}/${picture.height}`}
                alt="blahblahblah"
                width={picture.width}
                height={picture.height}
                title={picture.title}
              />
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
